
#define WALBERLA_LBM_CELLWISE_SWEEP_D3Q27_STREAM_COLLIDE_PULL() \
         const real_t vC   = src->get( x  , y  , z  , Stencil_T::idx[C]   ); \
         const real_t vN   = src->get( x  , y-1, z  , Stencil_T::idx[N]   ); \
         const real_t vS   = src->get( x  , y+1, z  , Stencil_T::idx[S]   ); \
         const real_t vW   = src->get( x+1, y  , z  , Stencil_T::idx[W]   ); \
         const real_t vE   = src->get( x-1, y  , z  , Stencil_T::idx[E]   ); \
         const real_t vT   = src->get( x  , y  , z-1, Stencil_T::idx[T]   ); \
         const real_t vB   = src->get( x  , y  , z+1, Stencil_T::idx[B]   ); \
         const real_t vNW  = src->get( x+1, y-1, z  , Stencil_T::idx[NW]  ); \
         const real_t vNE  = src->get( x-1, y-1, z  , Stencil_T::idx[NE]  ); \
         const real_t vSW  = src->get( x+1, y+1, z  , Stencil_T::idx[SW]  ); \
         const real_t vSE  = src->get( x-1, y+1, z  , Stencil_T::idx[SE]  ); \
         const real_t vTN  = src->get( x  , y-1, z-1, Stencil_T::idx[TN]  ); \
         const real_t vTS  = src->get( x  , y+1, z-1, Stencil_T::idx[TS]  ); \
         const real_t vTW  = src->get( x+1, y  , z-1, Stencil_T::idx[TW]  ); \
         const real_t vTE  = src->get( x-1, y  , z-1, Stencil_T::idx[TE]  ); \
         const real_t vBN  = src->get( x  , y-1, z+1, Stencil_T::idx[BN]  ); \
         const real_t vBS  = src->get( x  , y+1, z+1, Stencil_T::idx[BS]  ); \
         const real_t vBW  = src->get( x+1, y  , z+1, Stencil_T::idx[BW]  ); \
         const real_t vBE  = src->get( x-1, y  , z+1, Stencil_T::idx[BE]  ); \
         const real_t vTNE = src->get( x-1, y-1, z-1, Stencil_T::idx[TNE] ); \
         const real_t vTNW = src->get( x+1, y-1, z-1, Stencil_T::idx[TNW] ); \
         const real_t vTSE = src->get( x-1, y+1, z-1, Stencil_T::idx[TSE] ); \
         const real_t vTSW = src->get( x+1, y+1, z-1, Stencil_T::idx[TSW] ); \
         const real_t vBNE = src->get( x-1, y-1, z+1, Stencil_T::idx[BNE] ); \
         const real_t vBNW = src->get( x+1, y-1, z+1, Stencil_T::idx[BNW] ); \
         const real_t vBSE = src->get( x-1, y+1, z+1, Stencil_T::idx[BSE] ); \
         const real_t vBSW = src->get( x+1, y+1, z+1, Stencil_T::idx[BSW] );

#define WALBERLA_LBM_CELLWISE_SWEEP_D3Q27_COLLIDE_GET() \
        const real_t vC   = src->get( x, y, z, Stencil_T::idx[C]   ); \
        const real_t vN   = src->get( x, y, z, Stencil_T::idx[N]   ); \
        const real_t vS   = src->get( x, y, z, Stencil_T::idx[S]   ); \
        const real_t vW   = src->get( x, y, z, Stencil_T::idx[W]   ); \
        const real_t vE   = src->get( x, y, z, Stencil_T::idx[E]   ); \
        const real_t vT   = src->get( x, y, z, Stencil_T::idx[T]   ); \
        const real_t vB   = src->get( x, y, z, Stencil_T::idx[B]   ); \
        const real_t vNW  = src->get( x, y, z, Stencil_T::idx[NW]  ); \
        const real_t vNE  = src->get( x, y, z, Stencil_T::idx[NE]  ); \
        const real_t vSW  = src->get( x, y, z, Stencil_T::idx[SW]  ); \
        const real_t vSE  = src->get( x, y, z, Stencil_T::idx[SE]  ); \
        const real_t vTN  = src->get( x, y, z, Stencil_T::idx[TN]  ); \
        const real_t vTS  = src->get( x, y, z, Stencil_T::idx[TS]  ); \
        const real_t vTW  = src->get( x, y, z, Stencil_T::idx[TW]  ); \
        const real_t vTE  = src->get( x, y, z, Stencil_T::idx[TE]  ); \
        const real_t vBN  = src->get( x, y, z, Stencil_T::idx[BN]  ); \
        const real_t vBS  = src->get( x, y, z, Stencil_T::idx[BS]  ); \
        const real_t vBW  = src->get( x, y, z, Stencil_T::idx[BW]  ); \
        const real_t vBE  = src->get( x, y, z, Stencil_T::idx[BE]  ); \
        const real_t vTNE = src->get( x, y, z, Stencil_T::idx[TNE] ); \
        const real_t vTNW = src->get( x, y, z, Stencil_T::idx[TNW] ); \
        const real_t vTSE = src->get( x, y, z, Stencil_T::idx[TSE] ); \
        const real_t vTSW = src->get( x, y, z, Stencil_T::idx[TSW] ); \
        const real_t vBNE = src->get( x, y, z, Stencil_T::idx[BNE] ); \
        const real_t vBNW = src->get( x, y, z, Stencil_T::idx[BNW] ); \
        const real_t vBSE = src->get( x, y, z, Stencil_T::idx[BSE] ); \
        const real_t vBSW = src->get( x, y, z, Stencil_T::idx[BSW] );